### ISSUE TITLE
Authentication requires captcha input

### ISSUE THREAD

**Issue by HanlongLiao** [znck/grammarly#147] opened 2020-12-24 13:05 UTC
![1](https://user-images.githubusercontent.com/38033498/103090292-a32b6400-462b-11eb-820c-78c118f8d4ec.png)

The version is 0.12.5

**Comment by 5c0t-qi** [comment] 2020-12-25 02:33
Duplicate of #125

**Comment by YuvrajKhavad** [comment] 2020-12-27 07:45
Yes, I have the same error, Because grammarly.com add google captcha for login.

**Comment by znck** [comment] 2020-12-28 19:20
Duplicate of #107

**Closed by znck** 2020-12-28 19:20 UTC
