### ISSUE TITLE
 Paid Grammarly Account: captcha required while trying to log in

### ISSUE THREAD

**Issue by giorgiokrs** [znck/grammarly#125] opened 2020-08-17 15:46 UTC
When trying to log in to a paid account, a captcha is required: 

"Authentification requires captcha input."

And login fails.

Any idea of a possible solution?

![image](https://user-images.githubusercontent.com/69809138/90415358-433b1480-e0b1-11ea-93a4-6d9731cbc229.png)

------------------

**UPDATE:**

This requires support from the Grammarly Auth team. They have already implemented the necessary changes and waiting for release _(which is delayed due to holidays)_. Expecting this to be resolved in the first half of Jan 2020. 🥂

**Comment by sparshy** [comment] 2020-08-17 17:39
I am facing the same problem

**Comment by stderr-enst** [comment] 2020-08-18 07:29
This seems to be the open issue #107 - But unfortunately, I am affected as well since I had to log out a couple of days ago.

**Comment by matherm** [comment] 2020-09-02 06:52
Does logging out and in again several times help?

**Comment by boazbk** [comment] 2020-09-03 16:20
Same issue

**Comment by codeHatcher** [comment] 2020-09-05 21:14
any workarounds even? I'm having the same issue

**Comment by faguado-uvigo** [comment] 2020-09-06 21:21
Same issue. Any workaroud? Thnaks

**Comment by guillemf** [comment] 2020-09-09 11:04
Can't use it anymore. Same error on login.

**Comment by stevenybw** [comment] 2020-09-12 08:37
Can't log in anymore due to the captcha problem. I use VSCode to write academic papers. This extension is very important. Without this extension, Grammarly is meaningless to me.

**Comment by AlexMikhalev** [comment] 2020-09-22 19:42
Bump. Same here. No need to pay for Grammarly any more. 
Does anyone know a more human-friendly service? 
A

**Comment by AlexMikhalev** [comment] 2020-09-22 19:48
I submitted a ticket to Grammarly support. I encourage everyone struggling with this issue to do the same.

**Comment by cristianvasquez** [comment] 2020-09-26 01:14
I also will cancel my subscription because of this.

**Comment by stevenybw** [comment] 2020-09-26 04:51
> I submitted a ticket to Grammarly support. I encourage everyone struggling with this issue to do the same.

I've also submitted a ticket. But their response is that they won't officially support the integration to VSCode.

**Comment by AlexMikhalev** [comment] 2020-09-26 07:48
@stevenybw  they don't have to support it, just not to break it. I love Grammarly and used them from their very early beta, but now I am looking at alternatives, unfortunately very few. 
So far https://writefull.com/researchers.html#overleaf-learn-more-anchor looks promising.

**Comment by RaulDurand** [comment] 2020-09-29 03:09
> > I submitted a ticket to Grammarly support. I encourage everyone struggling with this issue to do the same.
> 
> I've also submitted a ticket. But their response is that they won't officially support the integration to VSCode.

They are probably working on its own extension.

**Comment by AlexMikhalev** [comment] 2020-09-29 08:44
In the meantime, I am evaluating https://sapling.ai/ , they also have Chrome extension, the ones who will cover most of my tools will have my money :)

**Comment by teefers** [comment] 2020-10-05 18:59
Having the same problem.  I Will cut a support ticket with Grammarly, but I don't expect much.  They seem to ignore support tickets.  All I want is the ability to use Markdown with Grammarly. 

Ther desktop App and Online editor converts all unordered list to there own bulleted list.  So you can't even copy and paste to check grammar.

**Comment by matherm** [comment] 2020-10-09 15:23
@AlexMikhalev Could you try the tool? Unfortunately, my scientific writing pipeline is still broken...

**Comment by znck** [comment] 2020-10-09 15:40
VS Code auth issues would be sorted soon (I don't have a timeline yet but project for providing auth support for this extension is approved.)

This extension is still unofficial (which means I still work on it over weekends). As soon as auth issue is resolved, I will notify.

**Comment by AlexMikhalev** [comment] 2020-10-12 09:01
@matherm looks like https://writefull.com/researchers.html#overleaf-learn-more-anchor was built specifically for academic work, maybe it will help you in the meantime.

**Comment by amacgregor** [comment] 2020-11-06 13:26
Any updates on captcha support?

**Comment by cristianvasquez** [comment] 2020-11-22 01:46
For some reason, it started working again for me

**Comment by adder46** [comment] 2020-11-22 06:39
> For some reason, it started working again for me

Not for me.

**Comment by learn2free** [comment] 2020-11-23 15:48
Same problem. waiting  for the update .

**Comment by Ayadmk** [comment] 2020-11-27 21:23
the same problem, no solution yet.

**Comment by Ayadmk** [comment] 2020-11-27 21:25
> 
> 
> For some reason, it started working again for me

how is it start at the beginning? because from the beginning, it did not work.

**Comment by Thomvaill** [comment] 2020-11-30 12:37
> VS Code auth issues would be sorted soon (I don't have a timeline yet but project for providing auth support for this extension is approved.)
> 
> This extension is still unofficial (which means I still work on it over weekends). As soon as auth issue is resolved, I will notify.

Is there a workaround to be able to log in in the meantime?

**Comment by wesleytian** [comment] 2020-12-04 03:48
@znck I will pay you if you can get this working

**Comment by znck** [comment] 2020-12-04 03:51
Fix is already in process, as soon as I get oauth client ID, I'll publish new version.

**Comment by wesleytian** [comment] 2020-12-04 05:22
Awesome! Send me your PayPal/venmo when you’re done :) I’ll buy you your next coffee.

**Comment by amacgregor** [comment] 2020-12-20 16:30
Hey @znck any updates yet?

**Comment by znck** [comment] 2020-12-20 16:36
🤞 hopefully this year. 

(PR was approved on Friday, the feature allows oauth for VS Code will go live in next release.)

**Comment by amacgregor** [comment] 2020-12-20 16:37
>  hopefully this year.
> 
> (PR was approved on Friday, the feature allowing oauth for VS Code will go live in next release.)

That's great news, also do you have any way to support you? Patreon, donations, etc?

**Comment by znck** [comment] 2020-12-20 16:50
[💖 GitHub Sponsors](http://github.com/sponsors/znck)

**Comment by senerdude** [comment] 2020-12-24 15:15
any progress on this?

**Comment by znck** [comment] 2020-12-28 19:20
Duplicate of #107

**Closed by znck** 2020-12-28 19:20 UTC

**Comment by geeeekDing** [comment] 2021-01-17 11:34
the same problem, no solution yet.

v0.12.5

**Comment by znck** [comment] 2021-01-17 11:35
WIP #148

**Comment by geeeekDing** [comment] 2021-01-17 11:45
> WIP #148

Thanks a lot,  I am looking forward to this fix.
