### ISSUE TITLE
Frequent high CPU usage

### ISSUE THREAD

**Issue by adder46** [znck/grammarly#146] opened 2020-12-24 09:33 UTC
The extension frequently jumps to 100% CPU usage and requires killing the process. To be fair, it does that with only one core.

![screenshot](https://i.ibb.co/L8qpVp3/Screenshot-2020-12-24-10-23-38.png)

**Comment by znck** [comment] 2020-12-28 19:23
Duplicate of #128

**Closed by znck** 2020-12-28 19:23 UTC
