### ISSUE TITLE
Stopped working even if logged in 

### ISSUE THREAD

**Issue by amacgregor** [znck/grammarly#183] opened 2021-04-11 17:24 UTC
Started getting the following error:

```
1618161793982 DEBUG  [TextGrammarCheckHost] (66696c) Hosting file:///Volumes/Workspace/Writing/Draft.dev/in-progress/Achieving%20Repeatability%20in%20Continuous%20Integration/Request.md
(node:392999) UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (/home/amacgregor/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38903:19)
    at GrammarlyClient._queueOrSend (/home/amacgregor/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38978:18)
    at /home/amacgregor/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38876:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (/home/amacgregor/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38874:16)
    at GrammarlyClient.start (/home/amacgregor/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:39160:21)
    at GrammarlyClient.onConnection [as _onConnection] (/home/amacgregor/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:39809:32)
(node:392999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by andylee830914** [comment] 2021-04-22 05:35
I got the same error these days.

**Comment by Shisagi** [comment] 2021-04-26 14:17
I am getting the same error.

**Comment by paolino** [comment] 2021-04-27 06:45
UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED

What to do?

Ironically, it's helping to write this comment :-|

**Comment by lucasfijen** [comment] 2021-04-27 13:11
Getting the same error

**Comment by znck** [comment] 2021-04-27 14:12
I'll try look into this today.

**Comment by znck** [comment] 2021-04-28 17:23
Couldn't reproduce. Need more info.

**Comment by beyefendi** [comment] 2021-04-28 21:08
```
(node:49088) UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (/home/emre/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38903:19)
    at GrammarlyClient._queueOrSend (/home/emre/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38978:18)
    at /home/emre/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38876:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (/home/emre/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:38874:16)
    at GrammarlyClient.start (/home/emre/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:39160:21)
    at GrammarlyClient.onConnection [as _onConnection] (/home/emre/.vscode/extensions/znck.grammarly-0.14.0/dist/server/index.js:39809:32)
(node:49088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by arnthorm** [comment] 2021-04-29 09:54
I was facing the same problem, I logged out (Grammarly: Logout of grammarly.com) and then it started to work again and was still working when I logged back in.

Maybe the token expired?

**Comment by ssbarnea** [comment] 2021-05-27 14:31
Any updates on this, the "login" popups that we cannot do anything about are a serious distraction.

**Comment by michidk** [comment] 2021-06-02 09:48
Getting the same error:
```
(node:16276) UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (c:\Users\michi\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38903:19)
    at GrammarlyClient._queueOrSend (c:\Users\michi\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38978:18)
    at c:\Users\michi\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38876:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (c:\Users\michi\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38874:16)
    at GrammarlyClient.start (c:\Users\michi\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:39160:21)
    at GrammarlyClient.onConnection [as _onConnection] (c:\Users\michi\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:39809:32)
(node:16276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Logging out and in again does not help. It works fine though on a different workstation.

**Comment by znck** [comment] 2021-07-14 03:28
The `NOT_AUTHORIZED` error code occurs when access token received from OAuth has expired. I haven't implemented token deletion or refreshing. However, as a workaround you can:

1. **Logout** using `Grammarly: Logout from grammarly.com`
2. **Reload**  or **Restart**  VS Code
3. **Login** using `Grammarly: Login to grammarly.com`

I don't have bandwidth to fix this issue right now but I am open to accepting PRs.

**Comment by znck** [comment] 2022-05-11 00:11
Fixed in v0.18.0

**Closed by znck** 2022-05-11 00:11 UTC
Labels: has workaround
